name: Python package build and publish

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # slow, but gets all the tags
    - name: Build manylinux2010 Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2010_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310'
        pre-build-command: source .github/workflows/wheel-prep.sh
        build-requirements: -rrequirements.txt -rmypy-requirements.txt
    - name: Move audited wheels to new directory
      run: mkdir audited_wheels && cp dist/*-manylinux*.whl audited_wheels/
